### ISSUE TITLE
Add support for generate-id()

### ISSUE THREAD

**Issue by raffazizzi** [ilinsky/jquery-xpath#18]
It looks like quite a few XPath 2.0 functions are not yet supported. `generate-id()` is one that is particularly useful: https://www.w3.org/2005/xpath-functions/#generate-id

**Comment by ilinsky** [comment]
Looks like there quite a set of changes had been done since the version https://www.w3.org/TR/2007/REC-xpath-functions-20070123/ I implemented..

Will catch up with https://www.w3.org/TR/xpath-functions/ with XPath 2.0 functions, but not yet http://www.w3.org/2005/xpath-functions/ which now is bound to XPath 3.0.
